### ISSUE TITLE
ConCache.update doesn't honor ttl configuration  

### ISSUE THREAD

**Issue by slashmili** [sasa1977/con_cache#22]
Hi,

If I create a process with `ttl` setting and later use `ConCache.update/3` to set the value:

```
ConCache.update(cache, :a, fn(_) -> {:ok, 1} end)
```

The `:a` item never gets expired. Is it correct behaviour? I'll push a failing scenario

**Comment by sasa1977** [comment]
This was indeed a bug, thanks for reporting. It's fixed in master through fefdd3376bc4661554f0406dccbc56f6df9027b1. I'll release 0.11.0 later today.

**Comment by slashmili** [comment]
Thanks for the quick fix!

**Comment by sasa1977** [comment]
FYI, the new version (0.11.0) is now deployed to hex.pm

**Comment by slashmili** [comment]
:+1:
