### ISSUE TITLE
Putting into wrong cache name hangs

### ISSUE THREAD

**Issue by Nagasaki45** [sasa1977/con_cache#36]
I started a cache with

```elixir
supervisor(ConCache, [[], [name: :queue]])
```

And then, by mistake, called `ConCache.put(:my_cache, :key, :value)` (notice the wrong cache name). The call just hangs. Wouldn't it be better for it to throw an exception instead?

Elixir: 1.4.4
con_cache: 0.12.0

**Comment by sasa1977** [comment]
Thanks for reporting!
