### ISSUE TITLE
Question: does this work across nodes?

### ISSUE THREAD

**Issue by jonathanleang** [sasa1977/con_cache#38]

**Comment by sasa1977** [comment]
No, `ConCache` is not a distributed cache. It is powered by [ets](http://erlang.org/doc/man/ets.html), so it only works in a scope of a single node. You can of course run one `ConCache` instance per each node and somehow synchronize the data or forward lookup/store operations to the proper node. However, how is this exactly supposed to be done is outside of the scope of `ConCache`.

**Comment by jonathanleang** [comment]
do you know which library I should look in to for something like that ?

**Comment by sasa1977** [comment]
This is the space where the whole ecosystem could use improvements. There are some solutions, but it's sort of not immediately clear how to start.

One possible solution is [riak_core](https://hex.pm/packages/riak_core_ng). This is the library which powered the Riak distributed database, and I believe in terms of algorithms that it's really solid. The bad news is that there are no clear and simple docs (as far as I know). Also, AFAIK Basho is not operating anymore, so the library is now maintained in a separate fork. Either way, a good place to find out more is [this excellent talk](https://www.youtube.com/watch?v=sYYOLaJ-VDQ). The repo which is linked on hex.pm is the fork where there's a lot of active development, so you may want to ask for help there.

Another option is to use [mnesia](http://erlang.org/doc/man/mnesia.html). With mnesia, it is possible to setup replicated tables (in-memory as well as disk based). You store the data on one node and it's replicated on all. The problem with mnesia is that it doesn't handle netsplits (though it provides the hooks for that), so you'll need to handle that yourself, or reach for something like [this](https://github.com/uwiger/unsplit).

There are some possible other solutions that could be helpful in some situations, such as [Phoenix presence](https://hexdocs.pm/phoenix/Phoenix.Presence.html) for example. I'd also advise asking around on elixirforum.com. I haven't been following this space closely for some time, so maybe some other solutions have emerged.

**Comment by jonathanleang** [comment]
@sasa1977  Thank you for your suggestions. 👍
