### ISSUE TITLE
Misleading readme file

### ISSUE THREAD

**Issue by IvanIvanoff** [sasa1977/con_cache#49]
In the readme file the last line contains `I don't maintain that project anymore, so I'm not aware of its current status.` although that claim is more than 3 years old. Since then a lot of changes have been done.
I guess it should be removed as it can make people look for other similar projects instead of trying this one.

**Comment by pap** [comment]
I guess the issue may be due to interpretation as I read it as if Sasa is refering to the project in prod using con_cache. I think that is the project he no longer maintains, the one he referred to regarding performance numbers.
