### ISSUE TITLE
Dirty Read

### ISSUE THREAD

**Issue by andrepaes** [sasa1977/con_cache#60]
Hello, is there a way to call the callback function after delete operation is done instead of before?

**Comment by sasa1977** [comment]
Callback is invoked before the delete to allow the users to read full data. If this is a problem because you're reading from the table and don't want to include the record which is about to be deleted, I suggest you simply filter that record out from the data you fetch from the table.

**Comment by andrepaes** [comment]
thanks for the suggestion! I thought that would have an built-in way to do it but it's ok.
